name: CI CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

permissions:
  contents: write
  packages: write

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: G-rez-l-int-gration-et-la-livraison-continue-Application-Java
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle
      - name: Run tests
        run: |
          chmod +x ../run-test.sh
          ../run-test.sh
      - name: Upload backend test reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: G-rez-l-int-gration-et-la-livraison-continue-Application-Java/test-results

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: G-rez-l-int-gration-et-la-livraison-continue-Application-Angular
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4 
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: G-rez-l-int-gration-et-la-livraison-continue-Application-Angular/package-lock.json
      - name: Run tests
        run: |
          chmod +x ../run-test.sh
          ../run-test.sh
      - name: Upload frontend test reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: G-rez-l-int-gration-et-la-livraison-continue-Application-Angular/test-results
  
  release:
    needs:
      - test-backend
      - test-frontend
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
      - name: Extract Version
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
  
  build-backend:
    needs: release 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with: 
          context:  G-rez-l-int-gration-et-la-livraison-continue-Application-Java
          file: G-rez-l-int-gration-et-la-livraison-continue-Application-Java/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/workshop-organizer-api:latest
            ghcr.io/${{ github.repository_owner }}/workshop-organizer-api:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/workshop-organizer-api:${{ needs.release.outputs.version }}
  build-frontend:
    needs: release 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with: 
          context:  G-rez-l-int-gration-et-la-livraison-continue-Application-Angular
          file: G-rez-l-int-gration-et-la-livraison-continue-Application-Angular/Dockerfile
          push: true
          tags: |
           ghcr.io/${{ github.repository_owner }}/olympic-app:latest
           ghcr.io/${{ github.repository_owner }}/olympic-app:${{ github.sha }}
           ghcr.io/${{ github.repository_owner }}/olympic-app:${{ needs.release.outputs.version }}
